#!/usr/bin/env bash
# Decrypt all sealed bundles and place them at canonical paths.
#
#   secrets/secrets.env.gpg              → ~/.envrc + ~/.claude/.credentials.json
#   secrets/files/ssh.tar.gz.gpg         → ~/.ssh/                (preserves 0600 perms)
#   secrets/files/gnupg.tar.gz.gpg       → ~/.gnupg/
#   secrets/files/codex-auth.json.gpg    → ~/.codex/auth.json
#   secrets/files/opencode-auth.json.gpg → ~/.local/share/opencode/auth.json
#
# Reads passphrase ONCE interactively; reuses for all bundles.
set -euo pipefail

GPG_DIR="$REPO_DIR/secrets"
ENV_GPG="$GPG_DIR/secrets.env.gpg"

[[ -f "$ENV_GPG" ]] || { echo "  [skip] no secrets.env.gpg"; exit 0; }

if [[ ${DRY_RUN:-0} -eq 1 ]]; then
  echo "[dry] gpg --decrypt $ENV_GPG → ~/.envrc + .credentials.json"
    [[ -f "$GPG_DIR/files/$f" ]] && echo "[dry] gpg --decrypt secrets/files/$f → (target path)"
  done
  exit 0
fi

PASS_FILE=$(mktemp)
trap 'shred -u "$PASS_FILE" 2>/dev/null || rm -f "$PASS_FILE"' EXIT
echo -n "  Passphrase: "
read -rs PASS
echo
printf '%s' "$PASS" > "$PASS_FILE"
unset PASS

decrypt() { gpg --batch --quiet --passphrase-file "$PASS_FILE" --decrypt "$1"; }

# === secrets.env.gpg → ~/.envrc + .credentials.json ===
TMP_ENV=$(mktemp)
trap 'shred -u "$PASS_FILE" "$TMP_ENV" 2>/dev/null || rm -f "$PASS_FILE" "$TMP_ENV"' EXIT
decrypt "$ENV_GPG" > "$TMP_ENV"
{
  echo "# Auto-generated by agent-treasures install at $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "# Source of truth: $ENV_GPG"
  echo ""
  grep -E '^[A-Z_]+=' "$TMP_ENV" | grep -v '^CLAUDE_CREDENTIALS_JSON=' | sed 's/^/export /'
} > "$HOME/.envrc"
chmod 600 "$HOME/.envrc"
echo "  wrote ~/.envrc (0600)"

if [[ ${FRESH_AUTH:-0} -eq 0 ]]; then
  creds_line=$(grep '^CLAUDE_CREDENTIALS_JSON=' "$TMP_ENV" || true)
  if [[ -n "$creds_line" ]]; then
    creds="${creds_line#CLAUDE_CREDENTIALS_JSON=}"
    mkdir -p "$HOME/.claude"
    printf '%s' "$creds" > "$HOME/.claude/.credentials.json"
    chmod 600 "$HOME/.claude/.credentials.json"
    echo "  wrote ~/.claude/.credentials.json"
  fi
else
  echo "  --fresh-auth: skipping .credentials.json"
fi

# === SSH bundle ===
if [[ -f "$GPG_DIR/files/ssh.tar.gz.gpg" ]]; then
  decrypt "$GPG_DIR/files/ssh.tar.gz.gpg" | tar -xzf - -C "$HOME"
  chmod 700 "$HOME/.ssh"
  find "$HOME/.ssh" -type f ! -name '*.pub' ! -name 'known_hosts*' ! -name 'config' -exec chmod 600 {} \;
  echo "  unpacked ~/.ssh/ (perms enforced)"
fi

# === GnuPG bundle ===
if [[ -f "$GPG_DIR/files/gnupg.tar.gz.gpg" ]]; then
  decrypt "$GPG_DIR/files/gnupg.tar.gz.gpg" | tar -xzf - -C "$HOME"
  chmod 700 "$HOME/.gnupg"
  echo "  unpacked ~/.gnupg/"
fi

# === Single-file app secrets ===
restore_file() {
  local sealed="$1" dst="$2" mode="$3"
  [[ -f "$sealed" ]] || return 0
  mkdir -p "$(dirname "$dst")"
  decrypt "$sealed" > "$dst"
  chmod "$mode" "$dst"
  echo "  wrote $dst (mode $mode)"
}

restore_file "$GPG_DIR/files/codex-auth.json.gpg"      "$HOME/.codex/auth.json"            600
restore_file "$GPG_DIR/files/opencode-auth.json.gpg"   "$HOME/.local/share/opencode/auth.json" 600

echo ""
echo "  reminder: in fresh zsh — \`direnv allow ~\` to pick up secrets."
